### ISSUE TITLE
enquiry

### ISSUE THREAD

**Issue by zenghaogithub** [khinthandarkyaw98/Optimizing-UAV-trajectory-for-maximum-data-rate-via-Q-Learning#2]
which platform did you use to run the code？i installed Airsim and UE4，then i run the code on Pycharm，but it didn't work。

**Comment by khinthandarkyaw98** [comment]
I am really sorry for the late reply! I just saw your question! We created an environment for UAV in Unreal Engine, applied Unreal Engine Blueprint to make random environment when the program starts.  To control the simulated UAV on UE, we used AirSim API.  We uploaded just codes we had written only and so you can't run.
