### ISSUE TITLE
the environment of mine does not have the airsim

### ISSUE THREAD

**Issue by 531669432** [khinthandarkyaw98/Optimizing-UAV-trajectory-for-maximum-data-rate-via-Q-Learning#3]
the environment of mine does not have the airsim,  if i only want to obtain the data of the Q-table, did i have to install the airsim?

**Comment by khinthandarkyaw98** [comment]
yes, you need to do so.

**Comment by 531669432** [comment]
> yes, you need to do so.

um, i have already install the airsim but i can not find the grid environment. thus the results of mine is not just like the shown version of the introduce. could you give me some advice to sovle this problem?

**Comment by khinthandarkyaw98** [comment]
hi, I am sorry to hear that, I am not sure if this could help you cos I cannot find the reference video that my friend and I watched together to do so, but I found out this one which seems to work although the grid in the vid is a lil different from us, I hope this would help you, please check out [https://www.youtube.com/watch?v=P_kVIOiTxo0](https://www.youtube.com/watch?v=P_kVIOiTxo0)

**Comment by khinthandarkyaw98** [comment]
what's more, you can refer to this doc [https://microsoft.github.io/AirSim/unreal_custenv/](https://microsoft.github.io/AirSim/unreal_custenv/) as well, hopefully, your problems are solved.

**Comment by 531669432** [comment]
thank you very much~~i will learn it
